spring:
  datasource:
    url: jdbc:mysql://ibebu-dev.cd4amyjhprms.us-west-1.rds.amazonaws.com:3306/db_ibebu
    username: admin
    password: "ibebu!#%#1353"
  jpa:
    properties:
      hibernate:
        format_sql: true
springdoc:
  server_url : https://dev.ibebu.net:3002
